# Generated by Django 4.1.3 on 2022-12-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_articles_alter_scope_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='Scopes',
        ),
    ]
