# Generated by Django 4.1.3 on 2022-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_articles_scope_article_rename_tags_scope_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
