# Generated by Django 4.1.3 on 2022-12-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_studentteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
    ]
