# Generated by Django 4.1.3 on 2022-12-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_student_teacher_student_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
