# Generated by Django 4.1.3 on 2022-12-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
